// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwGpkF_4Kl943CDYzVQMGmZ01xNoO6jag',
    appId: '1:329813303580:web:aafc55f2ebfe82bbba9ad9',
    messagingSenderId: '329813303580',
    projectId: 'newapp-964f7',
    authDomain: 'newapp-964f7.firebaseapp.com',
    storageBucket: 'newapp-964f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgwqEQYRauk7hhvChMH3I5BTPdu7aOf5U',
    appId: '1:329813303580:android:ca3915139b27f686ba9ad9',
    messagingSenderId: '329813303580',
    projectId: 'newapp-964f7',
    storageBucket: 'newapp-964f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Ix54Kk2_7YmCgbknFRMzV3PGzmex5ww',
    appId: '1:329813303580:ios:f89b7bc8dd5649d1ba9ad9',
    messagingSenderId: '329813303580',
    projectId: 'newapp-964f7',
    storageBucket: 'newapp-964f7.appspot.com',
    iosBundleId: 'com.example.sanjayflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1Ix54Kk2_7YmCgbknFRMzV3PGzmex5ww',
    appId: '1:329813303580:ios:5e614af60c89715cba9ad9',
    messagingSenderId: '329813303580',
    projectId: 'newapp-964f7',
    storageBucket: 'newapp-964f7.appspot.com',
    iosBundleId: 'com.example.sanjayflutterapp.RunnerTests',
  );
}
